CREATE TABLE IF NOT EXISTS "Bloque" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hora_inicio" time without time zone NOT NULL,
  "hora_final" time without time zone NOT NULL,
  "dia_id" bigint NOT NULL,
  "ubicacion_id" bigint NOT NULL,
  "ponencia_id" bigint NOT NULL
);

ALTER TABLE "Bloque" ADD FOREIGN KEY ("dia_id") REFERENCES "Dia" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Bloque" ADD FOREIGN KEY ("ubicacion_id") REFERENCES "Ubicacion" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Bloque" ADD FOREIGN KEY ("ponencia_id") REFERENCES "Ponencia" ("id") ON DELETE CASCADE ON UPDATE CASCADE;