CREATE TABLE IF NOT EXISTS "Asistencia" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date NOT NULL DEFAULT (CURRENT_DATE),
  "hora" time without time zone NOT NULL DEFAULT (CURRENT_TIME),
  "participante_id" bigint NOT NULL,
  "bloque_id" bigint NOT NULL,
  "congreso_id" bigint NOT NULL
);

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("participante_id") REFERENCES "Participante" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("bloque_id") REFERENCES "Bloque" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("congreso_id") REFERENCES "Congreso" ("id") ON DELETE CASCADE ON UPDATE CASCADE;