CREATE TABLE IF NOT EXISTS "Comentario" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "texto" varchar(255) NOT NULL,
  "fecha" date NOT NULL,
  "estado" bool NOT NULL DEFAULT true,
  "participante_id" bigint NOT NULL
);

ALTER TABLE "Comentario" ADD FOREIGN KEY ("participante_id") REFERENCES "Participante" ("id") ON DELETE CASCADE ON UPDATE CASCADE;