CREATE TABLE IF NOT EXISTS "Votacion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "score" bigint NOT NULL DEFAULT 0,
  "participante_id" bigint NOT NULL,
  "ponencia_id" bigint NOT NULL,
  "congreso_id" bigint NOT NULL
);

ALTER TABLE "Votacion" ADD FOREIGN KEY ("participante_id") REFERENCES "Participante" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Votacion" ADD FOREIGN KEY ("ponencia_id") REFERENCES "Ponencia" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Votacion" ADD FOREIGN KEY ("congreso_id") REFERENCES "Congreso" ("id") ON DELETE CASCADE ON UPDATE CASCADE;