CREATE TABLE IF NOT EXISTS "Congreso_Colaborador" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "congreso_id" bigint NOT NULL,
  "colaborador_id" bigint NOT NULL,
);
CREATE UNIQUE INDEX ON "Congreso_Colaborador" ("congreso_id", "colaborador_id");

ALTER TABLE "Congreso_Colaborador" ADD FOREIGN KEY ("congreso_id") REFERENCES "Congreso" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Congreso_Colaborador" ADD FOREIGN KEY ("colaborador_id") REFERENCES "Colaborador" ("id") ON DELETE CASCADE ON UPDATE CASCADE;