CREATE TABLE IF NOT EXISTS "Congreso_Administrador" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "congreso_id" bigint NOT NULL,
  "administrador_id" bigint NOT NULL
);
CREATE UNIQUE INDEX ON "Congreso_Administrador" ("congreso_id", "administrador_id");

ALTER TABLE "Congreso_Administrador" ADD FOREIGN KEY ("congreso_id") REFERENCES "Congreso" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Congreso_Administrador" ADD FOREIGN KEY ("administrador_id") REFERENCES "Administrador" ("id") ON DELETE CASCADE ON UPDATE CASCADE;