CREATE TABLE IF NOT EXISTS "Congreso" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date NOT NULL,
  "asistencia_total" bigint NOT NULL DEFAULT 0,
  "n_refrigerio" bigint NOT NULL DEFAULT 0,
  "estado" bool NOT NULL DEFAULT true,
  "escuela_profesional_id" bigint NOT NULL
);
ALTER TABLE "Congreso" ADD FOREIGN KEY ("escuela_profesional_id") REFERENCES "Escuela_profesional" ("id") ON DELETE CASCADE ON UPDATE CASCADE;