CREATE TABLE IF NOT EXISTS "Participante" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombres" varchar(40) NOT NULL,
  "ap_paterno" varchar(25) NOT NULL,
  "ap_materno" varchar(25) NOT NULL,
  "num_documento" varchar(20) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "tipo_participante_id" bigint NOT NULL,
  "escuela_profesional_id" bigint NOT NULL,
  "congreso_id" bigint NOT NULL,
  "estado" varchar(15) NOT NULL DEFAULT 'MATRICULADO',
  "qr_code" varchar(255)
);

ALTER TABLE "Participante" ADD FOREIGN KEY ("tipo_participante_id") REFERENCES "Tipo_participante" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Participante" ADD FOREIGN KEY ("escuela_profesional_id") REFERENCES "Escuela_profesional" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Participante" ADD FOREIGN KEY ("congreso_id") REFERENCES "Congreso" ("id") ON DELETE CASCADE ON UPDATE CASCADE;