CREATE TABLE IF NOT EXISTS "Ponente" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombres" varchar(40) NOT NULL,
  "apellidos" varchar(40) NOT NULL,
  "grado_academico" varchar(255) NOT NULL,
  "congreso_id" bigint NOT NULL
);

ALTER TABLE "Ponente" ADD FOREIGN KEY ("congreso_id") REFERENCES "Congreso" ("id") ON DELETE CASCADE ON UPDATE CASCADE;