CREATE TABLE IF NOT EXISTS "Colaborador" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombres" varchar(40) NOT NULL,
  "a_paterno" varchar(25) NOT NULL,
  "a_materno" varchar(25) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "estado" bool NOT NULL DEFAULT true,
  "escuela_profesional_id" bigint NOT NULL
);

ALTER TABLE "Colaborador" ADD FOREIGN KEY ("escuela_profesional_id") REFERENCES "Escuela_profesional" ("id") ON DELETE CASCADE ON UPDATE CASCADE;