CREATE TABLE IF NOT EXISTS "Refrigerio" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date NOT NULL,
  "hora" time without time zone NOT NULL,
  "participante_id" bigint NOT NULL,
  "congreso_id" bigint NOT NULL
);

ALTER TABLE "Refrigerio" ADD FOREIGN KEY ("congreso_id") REFERENCES "Congreso" ("id") ON DELETE CASCADE ON UPDATE CASCADE;