CREATE TABLE IF NOT EXISTS "Ponencia" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "estado" bool NOT NULL DEFAULT true,
  "ponente_id" bigint NOT NULL,
  "congreso_id" bigint NOT NULL
);

ALTER TABLE "Ponencia" ADD FOREIGN KEY ("ponente_id") REFERENCES "Ponente" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Ponencia" ADD FOREIGN KEY ("congreso_id") REFERENCES "Congreso" ("id") ON DELETE CASCADE ON UPDATE CASCADE;